# Core site settings
title = 'Some Recipes'
theme = 'hermit'
baseURL = 'https://some.recipes/'

# Language/text settings
languageCode = 'en-us'
defaultContentLanguage = 'en'
enableEmoji = true

# RSS settings
rssLimit = 10
copyright = '&#183; 2020 Shawn M. Chapla - CC BY-NC 4.0'

[author]
  name = 'Shawn M. Chapla'

[taxonomies]
  tag = 'tags'

[params]
  dateform        = 'Jan 2, 2006'
  dateformShort   = 'Jan 2'
  dateformNum     = '2006-01-02'
  dateformNumTime = '2006-01-02 15:04 -0700'

  description = 'A collection of recipes and food related content.'
  themeColor = '#494f5c'

  homeSubtitle = 'Ratios, techniques, and food related musings.'
  footerCopyright = ' &#183; <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

  # Social Icons
  [[params.social]]
    name = 'email'
    url = 'mailto:food@chapla.email'

  [[params.social]]
    name = 'twitter'
    url = 'https://twitter.com/shwnchpl'

  [[params.social]]
    name = 'github'
    url = 'https://github.com/shwnchpl'

[menu]

  [[menu.main]]
    name = 'Posts'
    url = 'posts/'
    weight = 10

  [[menu.main]]
    name = 'About'
    url = 'about/'
    weight = 20
